arch_params:
  arch: ResNet50
  num_classes: 100 # This is the number of classes for architecture FC layer.
  embedding_dim: 128
  last_nonlin: True
  norm_feature: True
  to_add_dim: 32
  C: 2

gallery_model_path: checkpoints/cifar100_old.pt
query_model_path: checkpoints/cifar100_transfer_new.pt.checkpoint


eval_params:
  distance_metric: cosine
  verbose: True
  compute_map: True
  per_class: False

dataset_params: # Test set of the dataset will be used as both gallery and query sets.
  name: cifar100
  data_root: data_store/cifar-100-python
  num_workers: 16
  batch_size: 256