arch_params:
  arch: ResNet50
  num_classes: 100 # This is the number of classes for architecture FC layer.
  embedding_dim: 128
  embedding_dim_old: 128
  last_nonlin: True
  norm_feature: True

optimizer_params:
  algorithm: adam
  lr: 0.001
  weight_decay: 0
  no_bn_decay: False
  momentum: 0.9
  nesterov: False

dataset_params:
  name: cifar100 
  data_root: data_store/cifar-100-python # /home/yz639/BCT/imagenet-1k # This should contain training and validation dirs.
  num_classes: 100 # This is the number of classes to include for training.
  num_workers: 16
  batch_size: 64

lr_policy_params:
  algorithm: cosine_lr
  warmup_length: 20
  epochs: 100
  lr: 0.001

epochs: 100
alpha: 10
old_model_path: checkpoints/cifar100_old.pt 
output_model_path: checkpoints/cifar100_bct.pt
