dataset_params:
  name: imagenet
  data_root: /home/yz639/BCT/ml-fct/data_store/imagenet-1k # This should contain training and validation dirs.
  num_classes: 1000 # This is the number of classes to include for training.
  num_workers: 16
  batch_size: 64

output_path: imagenet_captions.json
