arch_params:
  arch: ResNet50_ortho
  num_classes: 1000 # This is the number of classes for architecture FC layer.
  embedding_dim: 128
  embedding_dim_old: 128
  last_nonlin: True
  norm_feature: True
  to_add_dim: 32
  C: 2

optimizer_params:
  algorithm: adam
  lr: 0.001
  weight_decay: 0
  no_bn_decay: False
  momentum: 0.9
  nesterov: False

dataset_params:
  name: imagenet
  data_root: data_store/imagenet-1k # /home/yz639/BCT/imagenet-1k # This should contain training and validation dirs.
  num_classes: 100 # This is the number of classes to include for training.
  num_workers: 16
  batch_size: 1024

lr_policy_params:
  algorithm: cosine_lr
  warmup_length: 20
  epochs: 100
  lr: 0.001

epochs: 100
lambda_1: 1
lambda_2: 10
lambda_3: 5
old_model_path: checkpoints/imagenet_old.pt 
new_model_path: checkpoints/imagenet_new.pt
output_model_path: checkpoints/imagenet_transfer_new.pt
